问题：
在docker的fdfs进行上传文件报错
raise DataError('[-] Error: %d, %s' % (th.status, os.strerror(th.status)))

原因：出现此类问题的原因是因为storage启动时设置的IP或端口和python中链接文件（如：client.conf）中的IP地址不一致所导致的


解决方案：
将本机地址设置为固定IP后将本机IP和storage启动时设置的IP以及端口和python中链接文件（如：client.conf）中的IP地址保持一致
步骤：

第一步：设置本机固定IP

第二步：将storange停下后删除重新跑起来

命令如下：

sudo docker  container stop storage

sudo docker  container rm  storage

docker run -dti --network=host --name storage -e TRACKER_SERVER=192.168.233.131:22122 -v /var/fdfs/storage:/var/fdfs delron/fastdfs storage

sudo docker  container start storage

第三步：设置python中链接文件的IP
修改client.conf文件中的tracker_server配置ip
